# Generated by Django 3.2.6 on 2022-03-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_table_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='seats',
        ),
        migrations.AddField(
            model_name='table',
            name='totalseats',
            field=models.IntegerField(choices=[(2, 2), (4, 4), (6, 6), (12, 12)], default=2),
        ),
    ]
