# Generated by Django 3.2.6 on 2022-03-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220302_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='totalseats',
            new_name='seats',
        ),
    ]
