# Generated by Django 3.2.6 on 2022-03-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_totalseats_table_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
